apiVersion: apps/v1
kind: Deployment
metadata:
  name: transaction
  labels:
    app: transaction-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: transaction-service
  template:
    metadata:
      labels:
        app: transaction-service
    spec:
      containers:
      - name: transaction-app
        image: sbera717/transaction-service:v1
        ports:
        - containerPort: 8080