apiVersion: v1
kind: Service
metadata:
  name: transaction
  labels:
    app: transaction-service
spec:
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    app: transaction-service
  type: ClusterIP