apiVersion: apps/v1
kind: Deployment
metadata:
  name: test
  labels:
    app: java-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: java-app
  template:
    metadata:
      labels:
        app: java-app
    spec:
      containers:
      - name: test-app
        image: sbera717/java:{{ .Values.image.tag }}
        ports:
        - containerPort: 8080