apiVersion: apps/v1
kind: Deployment
metadata:
  name: login
  labels:
    app: login-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: login-service
  template:
    metadata:
      labels:
        app: login-service
    spec:
      containers:
      - name: login-app
        image: sbera717/login-service:v1
        ports:
        - containerPort: 8080