apiVersion: v1
kind: Service
metadata:
  name: login
  labels:
    app: login-service
spec:
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    app: login-service
  type: ClusterIP