apiVersion: apps/v1
kind: Deployment
metadata:
  name: wallet
  labels:
    app: wallet-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: wallet-service
  template:
    metadata:
      labels:
        app: wallet-service
    spec:
      containers:
      - name: wallet-app
        image: sbera717/wallet-service:v1
        ports:
        - containerPort: 8080