apiVersion: v1
kind: Service
metadata:
  name: wallet
  labels:
    app: wallet-service
spec:
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    app: wallet-service
  type: ClusterIP