apiVersion: apps/v1
kind: Deployment
metadata:
  name: user
  labels:
    app: user-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
      - name: user-app
        image: sbera717/user-service:{{ .Values.image.tag }}
        ports:
        - containerPort: 8080
