apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification
  labels:
    app: notification-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
      - name: wallet-app
        image: sbera717/notification-service:{{ .Values.image.tag }}
        ports:
        - containerPort: 8080
