apiVersion: v1
kind: Service
metadata:
  name: notification
  labels:
    app: notification-service
spec:
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    app: notification-service
  type: ClusterIP